# Generated by Django 5.2.1 on 2026-02-07 23:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wedding", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storyentry",
            options={"ordering": ["date"], "verbose_name_plural": "Story Entries"},
        ),
        migrations.AlterField(
            model_name="storyentry",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
