# Generated by Django 5.2.1 on 2026-02-08 23:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wedding", "0002_alter_storyentry_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storyentry",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
