# Generated by Django 5.2.1 on 2025-06-04 22:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dietary_restrictions', models.TextField(blank=True)),
                ('message_for_couple', models.TextField(blank=True)),
                ('attending', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
