# Generated by Django 5.2.1 on 2025-06-04 23:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='group_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
