# Generated by Django 5.2.1 on 2025-08-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_alter_guest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='dietary_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='message_for_couple',
            field=models.TextField(blank=True, null=True),
        ),
    ]
